# Generated by Django 3.0.2 on 2020-01-22 18:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacoes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avaliacao', models.IntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Enderecos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endereco', models.CharField(max_length=100)),
                ('bairro', models.CharField(max_length=100)),
                ('complemento', models.CharField(blank=True, max_length=100, null=True)),
                ('numero', models.IntegerField()),
                ('data_cadastro', models.DateField(default=django.utils.timezone.now)),
                ('cidade', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='restaurantes.Cidade')),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('uf', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurantes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=500)),
                ('foto', models.ImageField(null=True, upload_to='fotos/restaurantes', verbose_name='')),
                ('data_hora_cadastro', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('telefone', models.CharField(max_length=12)),
                ('endereco', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='restaurantes.Enderecos')),
            ],
            options={
                'unique_together': {('id', 'id')},
            },
        ),
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(max_length=255)),
                ('foto', models.ImageField(null=True, upload_to='fotos/comentarios', verbose_name='')),
                ('avaliacao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='restaurantes.Avaliacoes')),
            ],
        ),
        migrations.AddField(
            model_name='cidade',
            name='estado_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='restaurantes.Estado'),
        ),
        migrations.AddField(
            model_name='avaliacoes',
            name='restaurante',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='restaurantes.Restaurantes'),
        ),
    ]
