# Generated by Django 3.0.2 on 2020-01-22 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantes', '0002_auto_20200122_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantes',
            name='endereco',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='restaurantes.Enderecos'),
        ),
    ]
