# Generated by Django 3.0.2 on 2020-01-22 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantes', '0003_auto_20200122_1621'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enderecos',
            old_name='endereco',
            new_name='logradouro',
        ),
    ]
