# Generated by Django 3.0.2 on 2020-01-24 01:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantes', '0004_auto_20200122_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacoes',
            name='data_hora_cadastro',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='cidade',
            name='data_hora_cadastro',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='comentarios',
            name='data_hora_cadastro',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='enderecos',
            name='data_hora_cadastro',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='estado',
            name='data_hora_cadastro',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='restaurantes',
            name='data_hora_cadastro',
            field=models.DateTimeField(blank=True, default='2019-01-23'),
            preserve_default=False,
        ),
    ]
