# Generated by Django 3.0.2 on 2020-01-24 01:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantes', '0006_auto_20200123_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enderecos',
            name='data_cadastro',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='restaurantes',
            name='data_hora_cadastro',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
