# Generated by Django 3.0.2 on 2020-01-24 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantes', '0007_auto_20200123_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacoes',
            name='restaurante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurantes.Restaurantes'),
        ),
        migrations.AlterField(
            model_name='cidade',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurantes.Estado'),
        ),
        migrations.AlterField(
            model_name='enderecos',
            name='cidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurantes.Cidade'),
        ),
    ]
