# Generated by Django 3.0.2 on 2020-01-24 17:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantes', '0010_auto_20200123_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacoes',
            name='data_hora_cadastro',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='cidade',
            name='data_hora_cadastro',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='comentarios',
            name='data_hora_cadastro',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='enderecos',
            name='data_hora_cadastro',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='estado',
            name='data_hora_cadastro',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='restaurantes',
            name='data_hora_cadastro',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False),
        ),
    ]
